### ISSUE TITLE
Version command for Singularity 3 not working as intended

### ISSUE THREAD

**Issue by Flamefire** [singularityhub/singularity-cli#108]
## Expected Behavior

`get_singularity_version` returns `3.x`

## Actual Behavior

Returned is e.g. `singularity version 3.1.0-1`

## Possible Fix

Parse out version number

This affects e.g. checks like this: https://github.com/singularityhub/singularity-cli/blob/master/spython/main/export.py#L36

**Comment by vsoch** [comment]
This is a change in Singularity, not spython. The line to ask for `singularity --version` used to return a version number only, and now it is changed to this particular format. I asked about this, specifically for Spython, when it happened, and it is consistent with some standard. I believe it was on slack because I can't find an issue. I don't think it hurts to give the full version string, so until there is a strong reason to change it, it's not reasonable to change (and break any user code that expect this format).

**Comment by Flamefire** [comment]
Hm... The docstring says "get the singularity client version", so I'd expect an actual version, not the (full) output of `singularity --version`. This is IMO more convenient as you can e.g. do: `def get_mayor(version): return version.split(".")[0]`

If you want to keep the current behaviour I'd suggest to update the docstring

**Comment by vsoch** [comment]
Sure, happy to do that.

**Comment by vsoch** [comment]
What would you suggest to make it clear @Flamefire ?

**Comment by Flamefire** [comment]
Maybe:

> "get the singularity client version as reported by `singularity --version`"
> Examples: "2.0.1"
>                  "singularity version 3.0.1-1"

This highlights the format difference. But as mentioned: if there already is a wrapper function for getting a version I'd encapsulate the parsing into that function and just return the version itself (x.y.z...)

**Comment by vsoch** [comment]
This is fixed, the client now supports:

```
client.version_info()
```
along with 

```
client.version
```
And the functions driving that:

```python
from spython.utils import get_singularity_version, get_singularity_version_info
```
