### ISSUE TITLE
Parsing of native Singularity command

### ISSUE THREAD

**Issue by fbartusch** [singularityhub/singularity-cli#147]
**Is your feature request related to a problem? Please describe.**

I'm working on a tool for automatic provenance creation for scientific tools/workflows. The tool looks at a command and creates provenance metadata in xml format according to the PROV-standard. This is then visualized to show details about scientific computations like input/output files, used tools, etc. Now, I want to include support for basic Singularity commands like build, run, exec. Therefore have to parse the native Singularity command in order to do something useful with tools like spython or sif.

**Describe the solution you'd like**

I need a function that consumes Singularity commands, parses it, and returns objects I can use in my tool (like the container file, the Definition file, command line options, etc).
In principle, it's a reversed implementation of [this](https://github.com/singularityhub/singularity-cli/blob/master/spython/main/base/command.py)

**Describe alternatives you've considered**

Implementing this functionality myself. But I think it would be better to add it to singularity-cli. In principle, I could do the coding. I just wanted to ask first, if you want to include this functionality in this tool. Otherwise, I would just add it to my software.

**Additional context**

**Comment by vsoch** [comment]
Is the tool implemented in python (hence the choice of Singularity Python?) You don't think that it would make sense to either write something alongside Singularity (which is providing the arguments directly, or perhaps you could integrate with the argument parser directly? My thinking is that if this is done via Singularity Python, we have to maintain 1:1 correspondence with Singularity (really quite intensive in terms of work, likely to error with wrong versions, etc.) vs. with Singularity directly, the methods would be able to derive the arguments from the current install. So I'm interesting in helping out, but want to discuss possible other ideas:

 - a direct integration with Singularity to parse their arguments directly
 - a separate integration to parse a general command line output and generate a data structure
 
I'm liking the idea of a general tool, because wouldn't it be nice to be able to run for any general argument parser (e.g., you could make some parsers for GoLang, Python, etc.). Anyway, let me know your thoughts! This sounds like a cool project, but I think it would be really great to develop something that extends beyond a python wrapper for Singularity, both for extend-ability and ease of maintenance.

**Comment by fbartusch** [comment]
My tool is implemented in Python, hence I looked at this project.

> You don't think that it would make sense to either write something alongside Singularity (which is providing the arguments directly, or perhaps you could integrate with the argument parser directly?

I didn't really consider this, as Singularity is written in Go and I don't know if it could communicate with tools written in another programming language.

> My thinking is that if this is done via Singularity Python, we have to maintain 1:1 correspondence with Singularity

Yep, that would be a drawback. But don't you have the drawback already by having [this functionality?](https://github.com/singularityhub/singularity-cli/blob/master/spython/main/base/command.py)

> I'm liking the idea of a general tool, because wouldn't it be nice to be able to run for any general argument parser (e.g., you could make some parsers for GoLang, Python, etc.)

I didn't even thought about something like this, but that could be very nice. Let me get this right, you mean something that converts a Go argument parser (or an already existing go object) to something that can be used in another language? In this case Python?

**Comment by vsoch** [comment]
> Yep, that would be a drawback. But don't you have the drawback already by having this functionality?

Yes that's generally true for the upper level arguments, but if you look at any particular command group, I can generalize the options into an "options" string or list (see [here](https://github.com/singularityhub/singularity-cli/blob/master/spython/main/execute.py#L25) for exec, as an example. That way, the exec command options can change a lot, and the library doesn't need to be updated. If Singularity adds a new command group, this of course needs to be handled.

> I didn't even thought about something like this, but that could be very nice. Let me get this right, you mean something that converts a Go argument parser (or an already existing go object) to something that can be used in another language? In this case Python?

Yes! Even if you don't compile go directly, the observation I'd make is that most Python packages use argparser, and most Go packages use either [cobra](https://github.com/spf13/cobra) or the original flag, or a derivative like [https://github.com/spf13/pflag](https://github.com/spf13/pflag). And I bet when you look across the libraries, the output they generate is somewhat similar, and I wonder if that could be parsed? It would be really useful to have a general solution that "just works" or works for the most part - you'd probably need to identify the output patterns of the different libraries and then parse into a data structure.

Any reason to use xml? Can you show me documentation about this PROV standard? What is the end goal for its use? I ask because xml is ugly/scary for most, and the preferred these days seems to be json / yaml.

**Comment by fbartusch** [comment]
> It would be really useful to have a general solution that "just works" or works for the most part - you'd probably need to identify the output patterns of the different libraries and then parse into a data structure.

Ok, I'll take a look into this and invest some time in this.

> Any reason to use xml? Can you show me documentation about this PROV standard?

PROV is some kind of standarfd created by the W3C for provenance data in the web.
As alway, a good starting point is [Wikipedia](https://en.wikipedia.org/wiki/PROV_(Provenance)). It's a way to describe the relations between entities, agents, and activities. I use it to describe computations. For example, someone wants builds a new Singularity container. I want to capture: who built the container, on which machine, which Singularity version, information about the resulting container, etc. This information is saved as a provenance record.
Now someone uses this container for a computation on some input data and produces some output data. Then I want to capture information about this computation, but also include the information about the underlying container. For this, I need to get the parsed command.
XML is not mandatory, you can also save the information in other formats.

**Comment by vsoch** [comment]
> Ok, I'll take a look into this and invest some time in this.

okay great! Please ping me when you have thought more about it, I'd really enjoy helping. I really like projects like this!

And I think BMIR at Stanford (alongside my old graduate program) does a lot with PROV - I never ventured into doing much beyond using basic ontologies, and not in a very interesting way (just as dictionaries really). https://bmir.stanford.edu/ But now that I think about it, the ideas of entities, relationships, agents, activities, is very familiar, it also reminds me a bit of schema.org, which I've done some work with. Data structures... standards... are great :)
