### ISSUE TITLE
tweak to singularity recipe writer's handling of Dockerfile CMD instruction

### ISSUE THREAD

**Issue by ivotron** [singularityhub/singularity-cli#148]
## Expected Behavior

If we have a Dockerfile like this:

```Dockerfile
FROM alpine:3.8
ENTRYPOINT ["ls"]
CMD ["--help"]
```

executing:

```bash
spython recipe Dockerfile
```

should result in:

```
Bootstrap: docker
From: alpine:3.8
%runscript
exec ls "$@"
%startscript
exec ls --help "$@"
```

The above would allow to map between docker and singularity (assuming we build a `myimg` from the above Dockerfile):

```
docker run myimg  -->  singularity run myimg.sif

docker run myimg -la   -->   singularity run myimg.sif -la

docker run --entrypoint=/bin/another myimg  -->  singularity exec myimg.sif  /bin/another
```

without the above described behavior, the first two are not possible.

## Actual Behavior

The following is produced:

```
Bootstrap: docker
From: alpine:3.8
%runscript
exec /entrypoint.sh --help "$@"
%startscript
exec /entrypoint.sh --help "$@"
```

## Steps to Reproduce

create a Dockerfile with the above content, then execute the `spython recipe` command.

## Context

* Operating System: Ubuntu 18.04.3 LTS
* singularity version: 3.5.2+ds1
* spython version: 0.0.76
* python version: 3.6.9

**Comment by vsoch** [comment]
The recipe generated is only one line different from what you propose, e.g.,:

```
Bootstrap: docker
From: alpine:3.8
%runscript
exec ls --help "$@"
%startscript
exec ls --help "$@"
```
is what I'm generating locally, also with spython 0.0.76.  Your main issue is that you want the runscript to remove the `CMD` group, and although I understand this particular use case, that isn't logical for most use cases (where it's expected that the Dockerfile entrypoint and command are honored). 

I think what you are saying here is that if no arguments are provided, we want to add the command (--help) and otherwise we want to honor what the user has passed.

> docker run myimg  -->  singularity run myimg.sif
> docker run myimg -la   -->   singularity run myimg.sif -la
> docker run --entrypoint=/bin/another myimg  -->  singularity exec myimg.sif  /bin/another

The exec (the last one) would work as expected. The problem is that I don't see this translation as:

```
%runscript
exec ls "$@"
```
but rather something like (this is pseudocode)

```
%runscript
if there aren't arguments provided:
    exec ls --help
otherwise:
    exec ls "$@"
```
The issue is that actual run/entry points tend to be more complex than just one argument, and there are cases when you have something like:

```
ENTRYPOINT ["python"]
CMD ["/script.py"]
```
and the user would expect to be able to run the container without arguments and of course run the script:

```
singularity run container.sif
```
but also with arguments and (still) expect the script to be hit:

```
singularity run container.sif arg1 arg2
```

With your change, the recipe above would break, and the user would need to know the previous CMD and do this manually:

```
singularity exec container.sif /script.py arg1 arg2
```

So, it feels more dangerous to make the change, because (unlike an expert like yourself) most people don't use entrypoint / cmd correctly and would do something like that instead of:

```
ENTRYPOINT ["python", "/script.py"]
CMD ["--help"]
```
So - in that it's just a recipe converter, there is no way it can promise 100% accuracy, and in this case, you can just tweak the recipe to your needs. However, if you feel strongly about this, if you want to post some kind of poll (Twitter, Slack, or where you think is appropriate) and can provide support from others to make this change, I'd consider having something more akin to the if pseudocode that I showed above.

**Comment by ivotron** [comment]
thanks for taking the time to respond @vsoch !

> I think what you are saying here is that if no arguments are provided, we want to add the command (--help) and otherwise we want to honor what the user has passed.

yes, that's how `docker run` works. A simplification of the CLI interface is the following:

```
docker run IMAGE [ARGS]
```

if `ARGS` is not given, then whatever the `Dockerfile` specifies in the `CMD` instruction is used. However, if `ARGS` is given, it **overrides** the value of `CMD`. The current way in which the recipe is generated is not aligned to this. I think your above response assumes that `ARGS` gets _appended_ to `CMD` instead of overriding it (please correct me if I'm wrong)?

**Comment by vsoch** [comment]
Yes that's correct, my point is not to argue with the correct Docker usage, but to point out that many folks don't use it correctly, and would expect an entrypoint and cmd to both be included.

As I previously mentioned, I'm happy to make this change, but I'd like to see general support from the community that this is wanted, and also a suggested implementation that would be fool proof. If you'd like to open a PR I'd be happy to review it, and that might be a good way to point others to the PR and ask for feedback if the solution would work for them too.

**Comment by ivotron** [comment]
> Yes that's correct, my point is not to argue with the correct Docker usage, but to point out that many folks don't use it correctly, and would expect an entrypoint and cmd to both be included.

I'm not sure there's enough data that backs up the statement "many folks don't use it correctly". The `Dockerfile` semantics for `CMD` have been the same since the first Docker release, so it's not clear how people would expect both `ENTRYPOINT` and `CMD` to be executed when `docker run img` receives arguments. Or do you mean in the Singularity community, that's how people expect `CMD` to work in Docker?
 
> As I previously mentioned, I'm happy to make this change, but I'd like to see general support from the community that this is wanted, and also a suggested implementation that would be fool proof. If you'd like to open a PR I'd be happy to review it, and that might be a good way to point others to the PR and ask for feedback if the solution would work for them too.

sounds good. I'll create a PR and use that to survey the community.

thanks!
