### ISSUE TITLE
[BUG] Hypens in instance names

### ISSUE THREAD

**Issue by pierlauro** [singularityhub/singularity-cli#151]
Hi, I am wondering why at [instance start time](https://github.com/singularityhub/singularity-cli/blob/e325c628f680881a1eea9a62307cf1b3c1c85a98/spython/instance/__init__.py#L46) hyphens into instance names are being replaced by underscores.

I've checked that singularity 3.5.2 is actually supporting hyphens, was there any problem with previous versions? In that case, shouldn't the same behavior be implemented for instance list and stop?

The problem is clearly arising when using this library through `singularity-compose`. E.g. let's consider this `singularity-compose.yml`:
```yml
version: "1.0"
instances:
  x-y:
    build:
      context: ./images
```

When `docker-compose up` is called, the instance `x-y` is started with name `x_y`.  
When `docker-compose down`  is called, the instance `x_y` keeps living because the stop command was sent to the non-existent `x-y` instance.

I know that an obvious solution would be not to use hyphens, but sometimes we don't really have control on instance names (e.g. I discovered the bug because instance names with hypens have been automatically generated starting from a machine's hostname).

**Comment by vsoch** [comment]
It's not about creating the instances, but (at least an older version of Singularity) did not allow hashes in hostnames. See https://github.com/sylabs/singularity/blob/8f0ea1f8116a96ae573b336352ceaa08f851af8a/internal/pkg/util/fs/files/hostname.go. If that isn't fixed, then perhaps the best thing is to start the fix there, and then we can come and update here?

**Comment by pierlauro** [comment]
The [regex](https://github.com/sylabs/singularity/blob/8f0ea1f8116a96ae573b336352ceaa08f851af8a/internal/pkg/util/fs/files/hostname.go#L15) seems not to allow `-` just at the beginning and at the end of a name. Maybe the same regex should be ported in this library to validate names?

**Comment by vsoch** [comment]
That's a good suggestion, but I don't see a practical way to go about that (from uncompiled go to python?) even if we included the same string, we'd then have to watch it for changes and update.

To me this feels like a bug with Singularity - it should be allowed for a hostname that is generally acceptable (and maybe there is a reason they don't allow it?) I think it might make sense if we can reproduce your error (I triggered this a long time ago with https://github.com/researchapps/cvat/blob/add/singularity-compose/cvat/apps/documentation/singularity_user_guide.md#containers, see the last line linked in that section) so I don't have the exact way to reproduce.

Even if we did add this regex - would this fix your issue? Wouldn't we need singularity to fix this upstream? 

Also, in your first description above, did you mean `singularity-compose` when you said `docker-compose`? 

I think the easiest thing to do now is to add more enforcement on the names provided in the singularity-compose.yml, so you never hit a time when a dash is used. I typically do something like `namedb` instead of `name-db` for example.
