### ISSUE TITLE
Fail to runtest when building package for Debian/Ubuntu

### ISSUE THREAD

**Issue by Trophime** [singularityhub/singularity-cli#27]
Hi, trying to package singularity-cli I had some troubles running the test.

Is the module name "spython" or "singularity" because there are a lot of missing imports...?

Best
C

**Comment by vsoch** [comment]
spython

**Comment by vsoch** [comment]
I'm not sure what is going on, but you seem to be running tests for the singularity module using spython. Take a look in the spython code here - there is no tests folder!

**Comment by Trophime** [comment]
Actually I've dowloaded the file from here: https://pypi.org/project/spython/

**Comment by vsoch** [comment]
Trust me, I am on the same page. There is only one of me, and so many hours in the day! I hope the community can help out sometimes :)

**Comment by Trophime** [comment]
It will be great to have checks for basic functions as described in the [doc](https://singularityhub.github.io/singularity-cli/commands):
* Build an image from a recipe.
* Pull an image using Singularity
* Apps list the Scientific Filesystem apps in your image
* Inspect metadata about your image.
* Run execute the runscript for your image.
* Execute execute a command to the container

Just for the records, I've manage to get your tests working almost (see attached file - NB download-repo was commented out)
[spython-test.log](https://github.com/singularityhub/singularity-cli/files/1948185/spython-test.log)
I had to enable python3 support for singularity... As the 1srt move that could be to have these tests working

**Comment by vsoch** [comment]
hey @Trophime ! I have a PR in place that will add the basic tests you noted above. I couldn't add the test for the recipe with sudo but have a basic build without. I also didn't add a scientific apps recipe for that same reason, and I think this is fine for this first go because SCIF isn't standard / essential for Singularity (and if users want testing someone can PR to add it). I also set up the tests to run with travis using python 2 and 3! Here is the pull request  --> https://github.com/singularityhub/singularity-cli/pull/29 and the output on Travis --> https://travis-ci.org/singularityhub/singularity-cli/builds/371300161 Let me know if this is a good start and we can merge for spython version 0.0.30.

**Comment by Trophime** [comment]
Hi, great job thanks. That's perfect! :+1:

**Comment by Trophime** [comment]
I don't remember if there are tests also in sregistry-cli. If not it will be great to also have some basic tests.
