### ISSUE TITLE
PyPI "Project Description" Markdown

### ISSUE THREAD

**Issue by kmanalo** [singularityhub/singularity-cli#79]
**Is your feature request related to a problem? Please describe.**
https://pypi.org/project/spython/0.0.49/
I saw that the rendering of markdown wasn't done automatically on the above page.

**Describe the solution you'd like**
https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
Is it as easy as adding a line?

-Kevin

**Comment by vsoch** [comment]
Historically, Pypi (I think) expected restructured syntax. But it looks like the new warehouse server can accept a content type!

https://stackoverflow.com/questions/26737222/pypi-description-markdown-doesnt-work

I think this should work, given that I'm from Ubuntu - see this issue here:

https://github.com/pypa/warehouse/issues/3664

I'll be sure to update the setup.py on the next release! This is a great suggestion, it's super important that things are readable and look nice too :)

**Comment by vsoch** [comment]
This PR was merged, I can't say it's rendering correctly but we did do what (should) work.
